name: Update README.md
on:
  # repository_dispatchでサーバ側のymlで指定したevent-type `directory-changes`をフックする
  repository_dispatch:
    types: [update-a-blog-of-20210830]
  workflow_dispatch:

jobs:
  update-a-blog-of-20210830:
    name: Update README.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: | #このような書き方で複数行を一気に実行することができる。
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run main.py
        id: latest_data_id
        run: |
          python scripts/main.py

      - name: Update README.md
        run: |
          # すでに作成されているファイル (README.md) に修正が加わると、この then 以降の処理が走る。
          # 一方、gif が更新されずブログの文章のみが変更されがときは、上のスクリプトで README.md が更新されない。
          # したがって、以下の README.md の変更を表すコミットを打つ必要がない。
          if ! git diff --exit-code --quiet
          then
            git config --global user.name dilmnqvovpnmlib
            git config --global user.email dilmnqvovpnmlib@users.noreply.github.com
            git pull
            git add README.md
            git commit -m 'update README.md'
            git push origin main
          fi
