name: Update README.md
on:
  # repository_dispatchでサーバ側のymlで指定したevent-type `directory-changes`をフックする
  repository_dispatch:
    types: [update-a-blog-of-20210830]
jobs:
  update-a-blog-of-20210830:
    name: Update README.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: | #このような書き方で複数行を一気に実行することができる。
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run main.py
        id: latest_data_id
        run: |
          python scripts/main.py
          pwd
          ls

      - name: Update README.md
        run: |
          echo Hello
          git status
          if ! git diff --exit-code --quiet
          then
            git config --global user.name dilmnqvovpnmlib
            git config --global user.email dilmnqvovpnmlib@users.noreply.github.com
            git add README.md
            git commit -m 'update README.md'
            git push origin main
          fi
